### ISSUE TITLE
Use SqlPersistence instead of NHibernate persistence

### ISSUE THREAD

**Issue by jbogard** [Particular/Workshop#214]
Should simplify the saga data as well and remove any questions of "do we have to use NHibernate"

**Comment by jbogard** [comment]
Maybe I didn't see it - what's the problem with using `SqlSaga`?

**Comment by adamralph** [comment]
@jbogard `SqlSaga` is a special case just for the SQL persistence. At the moment we're considering how we can remove this wrinkle so that we can return to a single base class regardless of persistence choice. It's not a huge problem, but personally I'm a bit hesitant to showcase it in the workshop, given that it's ideally something we'd like to get rid of.

**Comment by DavidBoike** [comment]
Completed in #279
